# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_all

datas_pyd, binaries_pyd, hiddenimports_pyd = collect_all('pydantic')
datas_core, binaries_core, hiddenimports_core = collect_all('pydantic_core')
datas_fa, binaries_fa, hiddenimports_fa = collect_all('fastapi')
datas_star, binaries_star, hiddenimports_star = collect_all('starlette')
datas_uv, binaries_uv, hiddenimports_uv = collect_all('uvicorn')

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[] + binaries_pyd + binaries_core + binaries_fa + binaries_star + binaries_uv,
    datas=[
        ('frontend_dist', 'frontend_dist'),
        ('services/license/keys', 'services/license/keys'),
        ('prompts', 'prompts'),
        ('services', 'services'),
        ('database', 'database'),
        ('api', 'api'),
        ('scheduler', 'scheduler'),
        ('../version.json', '.'),

    ] + datas_pyd + datas_core + datas_fa + datas_star + datas_uv,
    hiddenimports=[
        'services',
        'services.system',
        'services.system.path_service',
        'services.system.tray_service',
        'services.system.diagnostic_service',
        'services.system.folder_picker',
        'services.watch_folder',
        'services.watch_folder_service',
        'services.watch_folder.engine',
        'services.watch_folder.scanner',
        'services.watch_folder.validator',
        'services.watch_folder.duplicate_checker',
        'services.watch_folder.importer',
        'services.upload_engine',
        'services.upload_engine.engine',
        'services.upload_service',
        'services.channel_service',
        'services.campaign_scan_service',
        'services.campaign_execution_service',
        'services.campaign_asset_service',
        'services.ai',
        'services.ai_engine',
        'services.ai.automation',
        'services.license',
        'scheduler',
        'scheduler.upload_scheduler',
        'scheduler.metadata_sync_scheduler',
        'database',
        'database.db',
        'models',
        'schemas',
        'api',
        'api.channels',
        'api.queue_router',
        'api.watch_folder',
        'api.upload_engine',
        'api.settings',
        'api.history',
        'api.dashboard',
        'api.import_api',
        'api.system',
        'api.media',
        'api.ai_engine',
        'api.license',
        'api.analytics',
        'api.campaign_assets',
        'api.campaign_scan',
        'api.campaign_review',
        'api.campaign_queue',
        'api.campaign_execution',
        'api.routers',
        'api.routers.oauth_router',
        'fastapi',
        'fastapi.applications',
        'fastapi.routing',
        'fastapi.responses',
        'fastapi.exceptions',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'starlette',
        'starlette.applications',
        'starlette.routing',
        'starlette.responses',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'passlib.handlers.bcrypt',
        'sqlite3',
        'sqlalchemy.ext.baked',
        'pydantic',
        'pydantic.validators',
        'pydantic_core',
        'pydantic_core._pydantic_core',
        'webview',
        'webview.platforms.winforms',
        'webview.platforms.edgechromium',
        'clr_loader',
        'google.auth._regional_access_boundary_utils',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'pystray',
    ] + hiddenimports_pyd + hiddenimports_core + hiddenimports_fa + hiddenimports_star + hiddenimports_uv,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='RaynzPitStop',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='../assets/icon.ico',
    version='file_version_info.txt'
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='RaynzPitStop',
)
