"""Add youtube_name to channels

Revision ID: 32c2d59bfa99
Revises: 9d3fb1e766df
Create Date: 2026-07-19 09:37:01.192020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c2d59bfa99'
down_revision: Union[str, Sequence[str], None] = '9d3fb1e766df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_assets', sa.Column('filepath', sa.String(), nullable=True))
    op.add_column('campaign_review_assets', sa.Column('sha256', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('youtube_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'youtube_name')
    op.drop_column('campaign_review_assets', 'sha256')
    op.drop_column('campaign_assets', 'filepath')
    # ### end Alembic commands ###
