"""missing_columns

Revision ID: 3b349eb34bc6
Revises: ba841b2732e8
Create Date: 2026-07-01 23:23:42.829344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b349eb34bc6'
down_revision: Union[str, Sequence[str], None] = 'ba841b2732e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('category', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('language', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('audience', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('license', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('thumbnail_rules', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('ai_preset', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('prompt_template', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('upload_tasks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('upload_tasks', sa.Column('pipeline_type', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('schedule_mode', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('schedule_time', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('humanize_enabled', sa.Boolean(), nullable=True))
    op.add_column('upload_tasks', sa.Column('humanize_min', sa.Integer(), nullable=True))
    op.add_column('upload_tasks', sa.Column('humanize_max', sa.Integer(), nullable=True))
    op.add_column('upload_tasks', sa.Column('upload_mode', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('ai_metadata_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_tasks', 'ai_metadata_generated')
    op.drop_column('upload_tasks', 'upload_mode')
    op.drop_column('upload_tasks', 'humanize_max')
    op.drop_column('upload_tasks', 'humanize_min')
    op.drop_column('upload_tasks', 'humanize_enabled')
    op.drop_column('upload_tasks', 'schedule_time')
    op.drop_column('upload_tasks', 'schedule_mode')
    op.drop_column('upload_tasks', 'pipeline_type')
    op.drop_column('upload_tasks', 'category_id')
    op.drop_column('profiles', 'is_default')
    op.drop_column('profiles', 'prompt_template')
    op.drop_column('profiles', 'ai_preset')
    op.drop_column('profiles', 'thumbnail_rules')
    op.drop_column('profiles', 'license')
    op.drop_column('profiles', 'audience')
    op.drop_column('profiles', 'language')
    op.drop_column('profiles', 'category')
    # ### end Alembic commands ###
