"""Add YouTube API metadata fields to UploadTask

Revision ID: 778a646bdbc1
Revises: b5157e0d276d
Create Date: 2026-06-24 22:17:52.009964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778a646bdbc1'
down_revision: Union[str, Sequence[str], None] = 'b5157e0d276d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_tasks', sa.Column('playlist_id', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('playlist_title', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('language', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('license', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('audience', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('notify_subscribers', sa.Boolean(), server_default="1", nullable=False))
    op.add_column('upload_tasks', sa.Column('embeddable', sa.Boolean(), server_default="1", nullable=False))
    op.add_column('upload_tasks', sa.Column('public_stats_viewable', sa.Boolean(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_tasks', 'public_stats_viewable')
    op.drop_column('upload_tasks', 'embeddable')
    op.drop_column('upload_tasks', 'notify_subscribers')
    op.drop_column('upload_tasks', 'audience')
    op.drop_column('upload_tasks', 'license')
    op.drop_column('upload_tasks', 'language')
    op.drop_column('upload_tasks', 'playlist_title')
    op.drop_column('upload_tasks', 'playlist_id')
    # ### end Alembic commands ###
