"""Initial Schema - Phase 3 Rebuild

Revision ID: 9d3fb1e766df
Revises: 
Create Date: 2026-07-12 18:40:10.118973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3fb1e766df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('fingerprint_version', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('asset_origin', sa.String(), nullable=True),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SELECTED', 'REVIEWED', 'APPROVED', 'UPLOADING', 'SCHEDULED', 'CONSUMED', 'ARCHIVED', name='campaignassetstate'), nullable=False),
    sa.Column('allow_reupload', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_assets_campaign_id'), 'campaign_assets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_assets_channel_id'), 'campaign_assets', ['channel_id'], unique=False)
    op.create_index(op.f('ix_campaign_assets_fingerprint'), 'campaign_assets', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_campaign_assets_youtube_video_id'), 'campaign_assets', ['youtube_video_id'], unique=False)
    op.create_table('campaign_review_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('pipeline_type', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detected', sa.Integer(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.Column('duplicate', sa.Integer(), nullable=True),
    sa.Column('invalid', sa.Integer(), nullable=True),
    sa.Column('selected_file_size', sa.Float(), nullable=True),
    sa.Column('selected_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_review_sessions_channel_id'), 'campaign_review_sessions', ['channel_id'], unique=False)
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_language', sa.String(), nullable=True),
    sa.Column('general_theme', sa.String(), nullable=True),
    sa.Column('general_launch', sa.Boolean(), nullable=True),
    sa.Column('general_update', sa.Boolean(), nullable=True),
    sa.Column('upload_concurrent', sa.Integer(), nullable=True),
    sa.Column('upload_retry', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('ai_api_key', sa.String(), nullable=True),
    sa.Column('ai_base_url', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('ai_temperature', sa.String(), nullable=True),
    sa.Column('ai_max_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_system_prompt', sa.String(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_timeout', sa.Integer(), nullable=True),
    sa.Column('ai_retry', sa.Integer(), nullable=True),
    sa.Column('notif_desktop', sa.Boolean(), nullable=True),
    sa.Column('notif_sound', sa.Boolean(), nullable=True),
    sa.Column('notif_success', sa.Boolean(), nullable=True),
    sa.Column('notif_fail', sa.Boolean(), nullable=True),
    sa.Column('perf_mode', sa.String(), nullable=True),
    sa.Column('perf_workers', sa.Integer(), nullable=True),
    sa.Column('perf_threads', sa.Integer(), nullable=True),
    sa.Column('perf_gpu', sa.Boolean(), nullable=True),
    sa.Column('perf_mem', sa.Integer(), nullable=True),
    sa.Column('app_density', sa.String(), nullable=True),
    sa.Column('app_color', sa.String(), nullable=True),
    sa.Column('app_anim', sa.Boolean(), nullable=True),
    sa.Column('app_compact', sa.Boolean(), nullable=True),
    sa.Column('adv_dev', sa.Boolean(), nullable=True),
    sa.Column('adv_logs', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('metadata_strategy', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('thumbnail_rules', sa.String(), nullable=True),
    sa.Column('ai_preset', sa.String(), nullable=True),
    sa.Column('prompt_template', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaign_review_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filesize', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('playlist', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('recording_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['campaign_review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_review_assets_fingerprint'), 'campaign_review_assets', ['fingerprint'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('subscribers', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('credential_folder', sa.String(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('quota_exhausted_until', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('watch_folder', sa.String(), nullable=True),
    sa.Column('watch_folder_enabled', sa.Boolean(), nullable=True),
    sa.Column('publish_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_publish_time', sa.String(), nullable=True),
    sa.Column('publish_timezone', sa.String(), nullable=True),
    sa.Column('publish_variance', sa.Integer(), nullable=True),
    sa.Column('publish_mode', sa.String(), nullable=True),
    sa.Column('publish_days', sa.String(), nullable=True),
    sa.Column('publish_visibility', sa.String(), nullable=True),
    sa.Column('review_before_publish', sa.Boolean(), nullable=True),
    sa.Column('import_folder', sa.String(), nullable=True),
    sa.Column('browser_profile', sa.String(), nullable=True),
    sa.Column('metadata_profile', sa.String(), nullable=True),
    sa.Column('upload_preset', sa.String(), nullable=True),
    sa.Column('playlist', sa.String(), nullable=True),
    sa.Column('upload_provider', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('ai_preset', sa.String(), nullable=True),
    sa.Column('upload_defaults', sa.String(), nullable=True),
    sa.Column('advanced_settings', sa.String(), nullable=True),
    sa.Column('ai_identity', sa.String(), nullable=True),
    sa.Column('schedule_profile', sa.String(), nullable=True),
    sa.Column('pipelines', sa.String(), nullable=True),
    sa.Column('pipeline_states', sa.String(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('profile_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_failed_count', sa.Integer(), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('last_refresh_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('upload_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('upload_stage', sa.String(), nullable=False),
    sa.Column('metadata_source', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('execution_source', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('execution_no', sa.Integer(), nullable=True),
    sa.Column('package_folder', sa.String(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('metadata_path', sa.String(), nullable=True),
    sa.Column('timestamps_path', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('privacy_status', sa.String(), nullable=False),
    sa.Column('made_for_kids', sa.Boolean(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('playlist_id', sa.String(), nullable=True),
    sa.Column('playlist_title', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('ai_use', sa.String(), nullable=False),
    sa.Column('default_language', sa.String(), nullable=True),
    sa.Column('audio_language', sa.String(), nullable=True),
    sa.Column('recording_date', sa.DateTime(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('notify_subscribers', sa.Boolean(), nullable=False),
    sa.Column('embeddable', sa.Boolean(), nullable=False),
    sa.Column('public_stats_viewable', sa.Boolean(), nullable=False),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('pipeline_type', sa.String(), nullable=True),
    sa.Column('schedule_mode', sa.String(), nullable=True),
    sa.Column('schedule_time', sa.String(), nullable=True),
    sa.Column('humanize_enabled', sa.Boolean(), nullable=True),
    sa.Column('humanize_min', sa.Integer(), nullable=True),
    sa.Column('humanize_max', sa.Integer(), nullable=True),
    sa.Column('upload_mode', sa.String(), nullable=True),
    sa.Column('ai_metadata_generated', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_seo_validation_at', sa.DateTime(), nullable=True),
    sa.Column('last_seo_provider', sa.String(), nullable=True),
    sa.Column('upload_progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_tasks_video_id'), 'upload_tasks', ['video_id'], unique=False)
    op.create_table('ai_generation_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('prompt_name', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('raw_response_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['upload_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_upload_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_session_id', sa.String(), nullable=False),
    sa.Column('campaign_asset_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('pipeline_type', sa.String(), nullable=False),
    sa.Column('publish_order', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.String(), nullable=False),
    sa.Column('publish_time', sa.String(), nullable=False),
    sa.Column('publish_datetime', sa.DateTime(), nullable=False),
    sa.Column('humanized_datetime', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('playlist', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('recording_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('execution_status', sa.Enum('PLANNED', 'READY', 'UPLOADING', 'UPLOADED', 'FAILED', 'CANCELLED', name='campaignexecutionstate'), nullable=False),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('execution_finished_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('execution_no', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('failure_category', sa.Enum('NETWORK', 'PLAYWRIGHT', 'LOGIN', 'YOUTUBE', 'VALIDATION', 'UNKNOWN', name='failurecategory'), nullable=True),
    sa.Column('retry_policy', sa.Enum('MANUAL', 'AUTO', name='retrypolicy'), nullable=False),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('youtube_publish_at', sa.DateTime(), nullable=True),
    sa.Column('upload_task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_asset_id'], ['campaign_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_session_id'], ['campaign_review_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_task_id'], ['upload_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_upload_plans_channel_id'), 'campaign_upload_plans', ['channel_id'], unique=False)
    op.create_table('upload_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['upload_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_upload_journal',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_upload_plan_id', sa.String(), nullable=False),
    sa.Column('upload_task_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('execution_no', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('browser_profile', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('failure_category', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_upload_plan_id'], ['campaign_upload_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_upload_journal_campaign_upload_plan_id'), 'campaign_upload_journal', ['campaign_upload_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_upload_journal_campaign_upload_plan_id'), table_name='campaign_upload_journal')
    op.drop_table('campaign_upload_journal')
    op.drop_table('upload_logs')
    op.drop_index(op.f('ix_campaign_upload_plans_channel_id'), table_name='campaign_upload_plans')
    op.drop_table('campaign_upload_plans')
    op.drop_table('ai_generation_history')
    op.drop_index(op.f('ix_upload_tasks_video_id'), table_name='upload_tasks')
    op.drop_table('upload_tasks')
    op.drop_table('oauth_credentials')
    op.drop_table('profile_templates')
    op.drop_table('channels')
    op.drop_index(op.f('ix_campaign_review_assets_fingerprint'), table_name='campaign_review_assets')
    op.drop_table('campaign_review_assets')
    op.drop_table('profiles')
    op.drop_table('global_settings')
    op.drop_index(op.f('ix_campaign_review_sessions_channel_id'), table_name='campaign_review_sessions')
    op.drop_table('campaign_review_sessions')
    op.drop_index(op.f('ix_campaign_assets_youtube_video_id'), table_name='campaign_assets')
    op.drop_index(op.f('ix_campaign_assets_fingerprint'), table_name='campaign_assets')
    op.drop_index(op.f('ix_campaign_assets_channel_id'), table_name='campaign_assets')
    op.drop_index(op.f('ix_campaign_assets_campaign_id'), table_name='campaign_assets')
    op.drop_table('campaign_assets')
    # ### end Alembic commands ###
