"""v5_architecture_lock

Revision ID: b5157e0d276d
Revises: 
Create Date: 2026-06-24 07:10:11.628076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5157e0d276d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('import_folder', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('browser_profile', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('metadata_profile', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('upload_preset', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('playlist', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('category', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('audience', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('license', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('language', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('ai_preset', sa.String(), nullable=True))
    op.drop_column('global_settings', 'yt_license')
    op.drop_column('global_settings', 'ai_preset')
    op.drop_column('global_settings', 'yt_category')
    op.drop_column('global_settings', 'yt_audience')
    op.drop_column('global_settings', 'upload_privacy')
    op.add_column('upload_tasks', sa.Column('upload_stage', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_tasks', 'upload_stage')
    op.add_column('global_settings', sa.Column('upload_privacy', sa.VARCHAR(), nullable=True))
    op.add_column('global_settings', sa.Column('yt_audience', sa.VARCHAR(), nullable=True))
    op.add_column('global_settings', sa.Column('yt_category', sa.VARCHAR(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_preset', sa.VARCHAR(), nullable=True))
    op.add_column('global_settings', sa.Column('yt_license', sa.VARCHAR(), nullable=True))
    op.drop_column('accounts', 'ai_preset')
    op.drop_column('accounts', 'language')
    op.drop_column('accounts', 'license')
    op.drop_column('accounts', 'audience')
    op.drop_column('accounts', 'category')
    op.drop_column('accounts', 'playlist')
    op.drop_column('accounts', 'upload_preset')
    op.drop_column('accounts', 'metadata_profile')
    op.drop_column('accounts', 'browser_profile')
    op.drop_column('accounts', 'import_folder')
    # ### end Alembic commands ###
