"""Add raw_response_json to AIGenerationHistory

Revision ID: ba841b2732e8
Revises: ce27ffdb5553
Create Date: 2026-06-27 19:22:09.427978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba841b2732e8'
down_revision: Union[str, Sequence[str], None] = 'ce27ffdb5553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_generation_history', sa.Column('raw_response_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_generation_history', 'raw_response_json')
    # ### end Alembic commands ###
