"""Add AI fields to global_settings

Revision ID: c8cd3f790716
Revises: cdc50fd48bbb
Create Date: 2026-06-27 05:43:55.190553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cd3f790716'
down_revision: Union[str, Sequence[str], None] = 'cdc50fd48bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('ai_provider', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_api_key', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_base_url', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_model', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_temperature', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_max_tokens', sa.Integer(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_system_prompt', sa.String(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_enabled', sa.Boolean(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_timeout', sa.Integer(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_retry', sa.Integer(), nullable=True))
    op.drop_column('global_settings', 'ai_gemini')
    op.drop_column('global_settings', 'ai_temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('ai_temp', sa.VARCHAR(), nullable=True))
    op.add_column('global_settings', sa.Column('ai_gemini', sa.BOOLEAN(), nullable=True))
    op.drop_column('global_settings', 'ai_retry')
    op.drop_column('global_settings', 'ai_timeout')
    op.drop_column('global_settings', 'ai_enabled')
    op.drop_column('global_settings', 'ai_system_prompt')
    op.drop_column('global_settings', 'ai_max_tokens')
    op.drop_column('global_settings', 'ai_temperature')
    op.drop_column('global_settings', 'ai_model')
    op.drop_column('global_settings', 'ai_base_url')
    op.drop_column('global_settings', 'ai_api_key')
    op.drop_column('global_settings', 'ai_provider')
    # ### end Alembic commands ###
