"""Add Review Metadata fields

Revision ID: cdc50fd48bbb
Revises: 778a646bdbc1
Create Date: 2026-06-26 06:47:38.807195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc50fd48bbb'
down_revision: Union[str, Sequence[str], None] = '778a646bdbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Profiles columns already exist in the database
    # category_id already added
    op.add_column('upload_tasks', sa.Column('ai_use', sa.String(), nullable=False, server_default='UNKNOWN'))
    op.add_column('upload_tasks', sa.Column('default_language', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('audio_language', sa.String(), nullable=True))
    op.add_column('upload_tasks', sa.Column('recording_date', sa.DateTime(), nullable=True))
    op.drop_column('upload_tasks', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_tasks', sa.Column('language', sa.VARCHAR(), nullable=True))
    op.drop_column('upload_tasks', 'recording_date')
    op.drop_column('upload_tasks', 'audio_language')
    op.drop_column('upload_tasks', 'default_language')
    op.drop_column('upload_tasks', 'ai_use')
    op.drop_column('upload_tasks', 'category_id')
    op.drop_column('profiles', 'is_default')
    op.drop_column('profiles', 'prompt_template')
    op.drop_column('profiles', 'ai_preset')
    op.drop_column('profiles', 'thumbnail_rules')
    op.drop_column('profiles', 'license')
    op.drop_column('profiles', 'audience')
    op.drop_column('profiles', 'language')
    op.drop_column('profiles', 'category')
    # ### end Alembic commands ###
