"""Add last_seo_validation fields to UploadTask

Revision ID: ce27ffdb5553
Revises: c8cd3f790716
Create Date: 2026-06-27 19:05:15.604203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce27ffdb5553'
down_revision: Union[str, Sequence[str], None] = 'c8cd3f790716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_tasks', sa.Column('last_seo_validation_at', sa.DateTime(), nullable=True))
    op.add_column('upload_tasks', sa.Column('last_seo_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_tasks', 'last_seo_provider')
    op.drop_column('upload_tasks', 'last_seo_validation_at')
    # ### end Alembic commands ###
